routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('home');
Route::group([
    'as' => 'client.',
    'namespace' => 'Client',
    ], function () {

    Route::resource('/vacancies', 'VacancyController', ['only' => ['index', 'show']]);
    Route::resource('/posts', 'PostController', ['only' => ['index', 'show']]);
    Route::resource('/raters', 'RaterController', ['only' => ['index', 'show']]);
    Route::resource('/messages', 'MessageController', ['only' => ['store']]);

    Route::get('/contacts', function () {
        return view('client.contacts');
    })->name('contacts');

    Route::get('/about', function () {
        return view('client.about');
    })->name('about');

    Route::get('/education', function () {
        return view('client.education');
    })->name('education');

    Route::resource('/documents', 'DocumentController', ['only' => ['index', 'show']]);
//    Route::group(['prefix' => 'documents'], function () {
//        Route::get('/', 'DocumentController@index')->name('documents.index');
//        Route::get('/{id}', 'DocumentController@show')->name('documents.show')->where('id', '[0-9]+');
//        Route::get('/charter', 'DocumentController@charter_index')->name('documents.charter.index');
//        Route::group(['prefix' => 'charter'], function () {
//            Route::get('/{id}', 'DocumentController@charter_show')->name('documents.charter.show');
//        });
//    });

});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth',
    'namespace' => 'Admin'
], function () {

    Route::get('/', 'AdminController@index')->name('admin');
    Route::resource('/users', 'UserController');
    Route::resource('/documents', 'DocumentController');
    Route::resource('/vacancies', 'VacancyController');
    Route::resource('/posts', 'PostController');
    Route::resource('/raters', 'RaterController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/messages', 'MessageController');
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'title',
        'icon',
        'body',
    ];

    protected $appends = [
        'fa_icon'
    ];

    public function faIcon()
    {
        return 'fa '. $this->icon;
    }

    public function getFaIconAttribute()
    {
        return $this->faIcon();
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        return view('admin.services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
            'icon' => 'required',
        ]);

        $service = new Service($request->all());
        $service->save();

        flash('Вакансия добавлена....', 'success');
        return redirect()->route('services.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $service = Service::findOrFail($id);
        return view('admin.services.show', compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::findOrFail($id);
        return view('admin.services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
            'icon' => 'required',
        ]);

        $service = Service::find($id);
        $service->update($request->all());
        $service->save();
        flash('Новость обновлена....', 'success');
        return redirect()->route('services.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        flash('Вакансия '. $service->title . ' удалена....', 'danger');
        $service->destroy($id);
        return redirect(route('services.index'));
    }
}

resources/views/admin/services/_form.blade.php
<div class="form-group">
    {!! Form::label('title', 'Название:') !!}
    {!! Form::text('title', null, [
            'class' => 'form-control',
            'required'
        ]) !!}
    @if($errors->has('title'))
        <span class="help-block">{{ $errors->first('title') }}</span>
    @endif
</div>

<div class="form-group">
    {!! Form::label('icon', 'Иконка:') !!}
    {!! Form::text('icon', null, [
            'class' => 'form-control',
            'required'
        ]) !!}
    @if($errors->has('icon'))
        <span class="help-block">{{ $errors->first('icon') }}</span>
    @endif
</div>

<div class="form-group">
    <label>Текст</label>
    {{ Form::textarea('body', null, ['class' => 'form-control', 'required']) }}
    @if($errors->has('body'))
        <span class="help-block">{{ $errors->first('body') }}</span>
    @endif
</div>

resources/views/admin/services/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Добавить
                </div>
                <div class="panel-body">

                    {!! Form::open(['route' => 'services.store', 'method' => 'POST', 'files'=>'true']) !!}
                    @include('admin.services._form')

                    <div class="form-group text-center">
                        {!! Form::submit('Создать', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/services/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="{{ $service->fa_icon }}"></i>
                    {{ $service->title }}
                </div>
                <div class="panel-body">

                    {!! Form::model($service, ['route' => ['services.update', $service->id], 'method' => 'PUT']) !!}
                    @include('admin.services._form')

                    <div class="form-group text-center">
                        {!! Form::submit('Изменить', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/services/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ route('services.create') }}" class="pull-right btn btn-xs btn-primary">
                        Добавить
                    </a>
                    Услуги
                </div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>icon</th>
                        <th>time</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($services as $service)
                        <tr>
                            <td>
                                <a href="{{ route('services.show', $service->id) }}">
                                    {{ $service->title }}
                                </a>
                            </td>
                            <td>
                                <i class="{{ $service->fa_icon }}"></i>
                            </td>
                            <td>{{ $service->created_at }}</td>
                            <td class="text-right">
                                <a href="{{ route('services.edit', $service->id) }}" class="btn btn-xs btn-warning">
                                    Изменить
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/services/show.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="javascript:;"
                       class="btn btn-xs btn-danger pull-right"
                       onclick="deleteTest({{ $service->id }})">
                        Удалить
                    </a>
                    <a style="margin-right: 15px" href="{{ route('services.edit', $service->id) }}" class="btn btn-xs btn-warning pull-right">
                        Изменить
                    </a>
                    <i class="{{ $service->fa_icon }}"></i>
                    {{ $service->title }}
                    <form id="delete-test-{{ $service->id }}" action="{{ route('services.destroy', $service->id) }}" method="post" style="display: none;">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                    </form>
                </div>
                <div class="panel-body">
                    <h1>
                        <i class="{{ $service->fa_icon }}"></i>
                        {{ $service->title }}
                    </h1>
                    <hr>
                    {!! $service->body !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    function deleteTest(id) {
        if (confirm('Вы действительно хотите удалить?')){
            event.preventDefault();
            document.getElementById('delete-test-' + id).submit();
        }
    }
</script>
@endpush