routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('home');
Route::group([
    'as' => 'client.',
    'namespace' => 'Client',
    ], function () {

    Route::resource('/vacancies', 'VacancyController', ['only' => ['index', 'show']]);
    Route::resource('/posts', 'PostController', ['only' => ['index', 'show']]);
    Route::resource('/raters', 'RaterController', ['only' => ['index', 'show']]);
    Route::resource('/messages', 'MessageController', ['only' => ['store']]);

    Route::get('/contacts', function () {
        return view('client.contacts');
    })->name('contacts');

    Route::get('/about', function () {
        return view('client.about');
    })->name('about');

    Route::get('/education', function () {
        return view('client.education');
    })->name('education');

    Route::resource('/documents', 'DocumentController', ['only' => ['index', 'show']]);
//    Route::group(['prefix' => 'documents'], function () {
//        Route::get('/', 'DocumentController@index')->name('documents.index');
//        Route::get('/{id}', 'DocumentController@show')->name('documents.show')->where('id', '[0-9]+');
//        Route::get('/charter', 'DocumentController@charter_index')->name('documents.charter.index');
//        Route::group(['prefix' => 'charter'], function () {
//            Route::get('/{id}', 'DocumentController@charter_show')->name('documents.charter.show');
//        });
//    });

});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth',
    'namespace' => 'Admin'
], function () {

    Route::get('/', 'AdminController@index')->name('admin');
    Route::resource('/users', 'UserController');
    Route::resource('/documents', 'DocumentController');
    Route::resource('/vacancies', 'VacancyController');
    Route::resource('/posts', 'PostController');
    Route::resource('/raters', 'RaterController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/messages', 'MessageController');
});

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacancy extends Model
{
    protected $fillable = [
        'title',
        'description',
        'body',
    ];
}

app/Http/Controllers/Admin/VacancyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Vacancy;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VacancyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vacancies = Vacancy::all();
        return view('admin.vacancies.index', compact('vacancies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.vacancies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
            'description' => 'required',
        ]);

        $vacancy = new Vacancy($request->all());
        $vacancy->save();

        flash('Вакансия добавлена....', 'success');
        return redirect()->route('vacancies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vacancy = Vacancy::findOrFail($id);
        return view('admin.vacancies.show', compact('vacancy'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vacancy = Vacancy::findOrFail($id);
        return view('admin.vacancies.edit', compact('vacancy'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
            'description' => 'required',
        ]);

        $vacancy = Vacancy::find($id);
        $vacancy->update($request->all());
        $vacancy->save();
        flash('Новость обновлена....', 'success');
        return redirect()->route('vacancies.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $vacancy = Vacancy::find($id);
        flash('Вакансия '. $vacancy->title . ' удалена....', 'danger');
        $vacancy->destroy($id);
        return redirect(route('vacancies.index'));
    }
}

app/Http/Controllers/Client/VacancyController.php
<?php

namespace App\Http\Controllers\Client;

use App\Post;
use App\Vacancy;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class VacancyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vacancies = Vacancy::all();
        $popular_posts = Post::limit(4)->orderBy('views', 'desc')->get();
        return view('client.vacancies.index', compact('vacancies', 'popular_posts'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vacancy = Vacancy::findOrFail($id);
        $raterKey = 'vacancy_' . $id;
        if (!Session::has($raterKey)) {
            Vacancy::where('id', $id)->increment('views');
            Session::put($raterKey, 1);
        }
        $popular_posts = Post::limit(4)->orderBy('views', 'desc')->get();
        return view('client.vacancies.show', compact('vacancy', 'popular_posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

}

resources/views/admin/vacancies/_form.blade.php
<div class="form-group">
    {!! Form::label('title', 'Название:') !!}
    {!! Form::text('title', null, [
            'class' => 'form-control',
            'required'
        ]) !!}
    @if($errors->has('title'))
        <span class="help-block">{{ $errors->first('title') }}</span>
    @endif
</div>
<div class="form-group">
    <label>Описание</label>
    {{ Form::textarea('description', null, ['class' => 'form-control']) }}
    @if($errors->has('description'))
        <span class="help-block">{{ $errors->first('description') }}</span>
    @endif
</div>
<div class="form-group">
    <label>Текст</label>
    {{ Form::textarea('body', null, ['id' => 'article-ckeditor', 'required']) }}
    @if($errors->has('body'))
        <span class="help-block">{{ $errors->first('body') }}</span>
    @endif
</div>

resources/views/admin/vacancies/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Добавить вакансию
                </div>
                <div class="panel-body">

                    {!! Form::open(['route' => 'vacancies.store', 'method' => 'POST', 'files'=>'true']) !!}
                    @include('admin.vacancies._form')

                    <div class="form-group text-center">
                        {!! Form::submit('Создать', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vacancies/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $vacancy->title }}
                </div>
                <div class="panel-body">

                    {!! Form::model($vacancy, ['route' => ['vacancies.update', $vacancy->id], 'method' => 'PUT']) !!}
                    @include('admin.vacancies._form')

                    <div class="form-group text-center">
                        {!! Form::submit('Изменить', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vacancies/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ route('vacancies.create') }}" class="pull-right btn btn-xs btn-primary">
                        Добавить
                    </a>
                    Вакансии
                </div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th></th>
                        <th>views</th>
                        <th>time</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($vacancies as $post)
                        <tr>
                            <td>
                                <a href="{{ route('vacancies.show', $post->id) }}">
                                    {{ $post->title }}
                                </a>
                            </td>
                            <td>{{ $post->description }}</td>
                            <td>{{ $post->views }}</td>
                            <td>{{ $post->created_at }}</td>
                            <td class="text-right">
                                <a href="{{ route('vacancies.edit', $post->id) }}" class="btn btn-xs btn-warning">
                                    Изменить
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vacancies/show.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="javascript:;"
                       class="btn btn-xs btn-danger pull-right"
                       onclick="deleteTest({{ $vacancy->id }})">
                        Удалить
                    </a>
                    <a style="margin-right: 15px" href="{{ route('vacancies.edit', $vacancy->id) }}" class="btn btn-xs btn-warning pull-right">
                        Изменить
                    </a>
                    {{ $vacancy->title }}
                    <form id="delete-test-{{ $vacancy->id }}" action="{{ route('vacancies.destroy', $vacancy->id) }}" method="post" style="display: none;">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                    </form>
                </div>
                <div class="panel-body">
                    <h1>
                        {{ $vacancy->title }}
                    </h1>
                    <div class="img-rounded">
                        <img src="{{ $vacancy->photo }}" alt=""  height="400">
                    </div>
                    <hr>
                    {!! $vacancy->body !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    function deleteTest(id) {
        if (confirm('Вы действительно хотите удалить?')){
            event.preventDefault();
            document.getElementById('delete-test-' + id).submit();
        }
    }
</script>
@endpush