routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('home');
Route::group([
    'as' => 'client.',
    'namespace' => 'Client',
    ], function () {

    Route::resource('/vacancies', 'VacancyController', ['only' => ['index', 'show']]);
    Route::resource('/posts', 'PostController', ['only' => ['index', 'show']]);
    Route::resource('/raters', 'RaterController', ['only' => ['index', 'show']]);
    Route::resource('/messages', 'MessageController', ['only' => ['store']]);

    Route::get('/contacts', function () {
        return view('client.contacts');
    })->name('contacts');

    Route::get('/about', function () {
        return view('client.about');
    })->name('about');

    Route::get('/education', function () {
        return view('client.education');
    })->name('education');

    Route::resource('/documents', 'DocumentController', ['only' => ['index', 'show']]);
//    Route::group(['prefix' => 'documents'], function () {
//        Route::get('/', 'DocumentController@index')->name('documents.index');
//        Route::get('/{id}', 'DocumentController@show')->name('documents.show')->where('id', '[0-9]+');
//        Route::get('/charter', 'DocumentController@charter_index')->name('documents.charter.index');
//        Route::group(['prefix' => 'charter'], function () {
//            Route::get('/{id}', 'DocumentController@charter_show')->name('documents.charter.show');
//        });
//    });

});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth',
    'namespace' => 'Admin'
], function () {

    Route::get('/', 'AdminController@index')->name('admin');
    Route::resource('/users', 'UserController');
    Route::resource('/documents', 'DocumentController');
    Route::resource('/vacancies', 'VacancyController');
    Route::resource('/posts', 'PostController');
    Route::resource('/raters', 'RaterController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/messages', 'MessageController');
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $fillable = [
        'title',
        'doc',
        'body',
        'description',
    ];

    protected $appends = [
        'doc_link'
    ];

    public function link()
    {
        return $this->doc ? env('APP_URL') . '/' . $this->doc : '';
    }

    public function getDocLinkAttribute()
    {
        return $this->link();
    }
}

app/Http/Controllers/Admin/DocumentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Document;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $documents = Document::all();
        return view('admin.documents.index', compact('documents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.documents.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            'doc_name' => 'required|mimes:pdf,doc,docx'
        ]);

        $document = new Document($request->all());
        $document->is_act = $request->input('is_act') ? 1 : 0;

        if(isset($request['doc_name'])) {
            $file = $request->file('doc_name');
            $fname = substr(md5(microtime()), 0, 6);
            $path = $file->storeAs('docs', $fname . '.' . $file->getClientOriginalExtension());
            $document->doc = 'storage/' . $path;
        }
        $document->save();

        flash('Документ добавлен....', 'success');
        return redirect()->route('documents.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $document = Document::findOrFail($id);
        return view('admin.documents.show', compact('document'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = Document::findOrFail($id);
        return view('admin.documents.edit', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
        ]);

        $document = Document::find($id);
        $document->update($request->all());
        if(isset($request['doc_name']))
        {
            $file = $request->file('doc_name');
            $fname = substr(md5(microtime()), 0, 6);
            $path = $file->storeAs('docs', $fname . '.' . $file->getClientOriginalExtension());
            $document->doc = 'storage/' . $path;
        }
        $document->save();
        flash('Документ обновлена....', 'success');
        return redirect()->route('documents.show', $id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $document = Document::find($id);
        flash('Документ '. $document->title . ' удалена....', 'danger');
        if($document->doc) {
            $filename = $document->doc;
            Storage::delete(substr($filename, -15));
        }

        $document->destroy($id);
        return redirect(route('documents.index'));
    }
}

app/Http/Controllers/Client/DocumentController.php
<?php

namespace App\Http\Controllers\Client;

use App\Document;
use App\Http\Controllers\Controller;
use App\Post;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $documents = Document::limit(10)->orderBy('title')->paginate(10);
        $popular_posts = Post::limit(4)->orderBy('views', 'desc')->get();
        return view('client.documents.index', compact('popular_posts', 'documents'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $document = Document::findOrFail($id);
        $popular_posts = Post::limit(4)->orderBy('views', 'desc')->get();
        return view('client.documents.show', compact('document', 'popular_posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

}

resources/views/admin/documents/_form.blade.php
<div class="form-group">
    {!! Form::label('title', 'Название:') !!}
    {!! Form::text('title', null, [
            'class' => 'form-control',
            'required'
        ]) !!}
    @if($errors->has('title'))
        <span class="help-block">{{ $errors->first('title') }}</span>
    @endif
</div>

<div class="form-group">
    <label>Описание</label>
    {{ Form::textarea('description', null, ['class' => 'form-control', 'required']) }}
    @if($errors->has('description'))
        <span class="help-block">{{ $errors->first('description') }}</span>
    @endif
</div>

<div class="form-group">
    <label>Подробное Описание</label>
    {{ Form::textarea('body', null, ['id' => 'article-ckeditor']) }}
    @if($errors->has('body'))
        <span class="help-block">{{ $errors->first('body') }}</span>
    @endif
</div>

<hr>

<div class="form-group">
    {!! Form::label('doc_name', 'Документ: (pdf,doc,docx, xlsx,xls)') !!}
    {!! Form::file('doc_name', ['class' => 'form-control']) !!}
    @if($errors->has('doc_name'))
        <span class="help-block">{{ $errors->first('doc_name') }}</span>
    @endif
</div>

resources/views/admin/documents/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Добавить документ
                </div>
                <div class="panel-body">

                    {!! Form::open(['route' => 'documents.store', 'method' => 'POST', 'files'=>'true']) !!}
                    @include('admin.documents._form')

                    <div class="form-group text-center">
                        {!! Form::submit('Создать', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/documents/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $document->title }}
                </div>
                <div class="panel-body">

                    {!! Form::model($document, ['route' => ['documents.update', $document->id], 'method' => 'PUT', 'files'=>'true']) !!}
                    @include('admin.documents._form')

                    <a href="{{ $document->doc_link }}" download>Документ</a>

                    <div class="form-group text-center">
                        {!! Form::submit('Изменить', ['class' => 'btn btn-primary btn-lg']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/documents/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ route('documents.create') }}" class="pull-right btn btn-xs btn-primary">
                        Добавить
                    </a>
                    Документы
                </div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Doc</th>
                        <th>time</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($documents as $document)
                        <tr>
                            <td>
                                <a href="{{ route('documents.show', $document->id) }}">
                                    {{ $document->title }}
                                </a>
                            </td>
                            <td>{{ $document->description }}</td>
                            <td>
                                <a href="{{ $document->doc_link }}" target="_blank" download>
                                    Документ
                                    <i class="fa fa-download"></i>
                                </a>
                            </td>
                            <td>{{ $document->created_at }}</td>
                            <td class="text-right">
                                <a href="{{ route('documents.edit', $document->id) }}" class="btn btn-xs btn-warning">
                                    Изменить
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/documents/show.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="javascript:;"
                       class="btn btn-xs btn-danger pull-right"
                       onclick="deleteTest({{ $document->id }})">
                        Удалить
                    </a>
                    <a style="margin-right: 15px" href="{{ route('documents.edit', $document->id) }}" class="btn btn-xs btn-warning pull-right">
                        Изменить
                    </a>
                    {{ $document->title }}
                    <form id="delete-test-{{ $document->id }}" action="{{ route('documents.destroy', $document->id) }}" method="post" style="display: none;">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                    </form>
                </div>
                <div class="panel-body">
                    <h1>
                        {{ $document->title }}
                    </h1>
                    <hr>
                    <a href="{{ $document->doc_link }}" download>Документ</a>
                    <p>
                        {{ $document->description }}
                    </p>
                    {!! $document->body !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    function deleteTest(id) {
        if (confirm('Вы действительно хотите удалить?')){
            event.preventDefault();
            document.getElementById('delete-test-' + id).submit();
        }
    }
</script>
@endpush